# Site settings
title: Sun Biao
email: bsuntju@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Institute of Robotics and Autonomous Systems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sunbiao.me" # the base hostname & protocol for your site
twitter_username: sunbiao
github_username:  sunbiaoex

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"
